### PR TITLE
Use strings.Replacer to allocate Replace up front instead of in each loop iteration.

### PR DESCRIPTION
**Pull request by nibbleshift**
~Instead of using encoding/json, switch to go-json.~

Use a strings.Replacer instead of multiple calls to strings.Replace.

### CODE REVIEW

**Comment by Jeffail** [comment]
Hey @nibbleshift, sorry this took so long, can you separate the change to `go-json` into a separate PR? I definitely want the strings.Replacer stuff but I'm not sure it's worth switching to a third party library for JSON parsing since this lib doesn't force you to use it for the parsing/formatting stuff anyway.

**Comment by nibbleshift** [comment]
Sure thing, I'll go ahead and create a PR for the replacer stuff.

**Comment by nibbleshift** [comment]
Sorry this took so long.  I've removed the go-json dependency from this PR.

**Comment by Jeffail** [comment]
Thanks @nibbleshift!

**Pull request merged**
