### PR TITLE
Deep-merge of two containers

### PR DESCRIPTION
**Pull request by TobiEiss**
- Impl a merge-function to merge a second container.
- Also tests for merge-function
- And docu in README how to use merge-function

### CODE REVIEW

**Comment by Jeffail** [comment]
Hey @TobiEiss, I think a merge function is a great idea but I would expect slightly different behaviour from it than what you've implemented here. For example, I would expect elements within merged sibling arrays to become a single array, rather than one being nested within the other:

```
{"array": ["one"]} + {"array": ["two"]} = {"array": ["one", "two"]}
```

I would also expect colliding values to become arrays:

```
{"value": "one"} + {"value": "two"} = {"value": ["one", "two"]}
```
Unless it is implemented this way with a specific purpose in mind I think I'd prefer it to work this way. I've added some test cases to demonstrate what I mean.

**Comment by Jeffail** [comment]
Test cases here: https://github.com/Jeffail/gabs/commit/c429fd674ed41f0aeb7bf7f703d7faa813e0e774

**Comment by TobiEiss** [comment]
Hey @Jeffail 
i have:
- implemented your ideas
- assume your tests
- fit README

Please notice my changes in the function `ArrayAppend` (https://github.com/Jeffail/gabs/pull/39/files#diff-61bc25115be701aeefba42a3a7ed03cdR360).

**Comment by Jeffail** [comment]
Awesome, thanks a lot @TobiEiss! I've added some more test cases (basically reversed the previous ones) and made sure they pass. Really happy with this addition, it's a very useful feature.

**Pull request merged**
